### PR TITLE
settings: update aim_strings.xml

### PR DESCRIPTION
**Pull request by shirofficial**

### CODE REVIEW

**Review by krasCGQ — APPROVED** [review]

**Comment by krasCGQ** [comment]
When GitHub decides to become dumb. Re-closing PR.

**Comment by Anandnv** [comment]
lmao @krasCGQ  boooooo

**Comment by krasCGQ** [comment]
Manual merge ftw

**Comment by yankit293** [comment]
@krasCGQ Lol

**Comment by yankit293** [comment]
@yankit293 Noob

**Pull request closed without merging**
