### PR TITLE
Add Co-maintainer for lenovo a7000

### PR DESCRIPTION
**Pull request by AryanKedare**

### CODE REVIEW

**Comment by Anandnv** [comment]
we dropped N . working on oreo.

**Comment by AryanKedare** [comment]
Actually i was busy with studies so one guy compiled and gave the final version so need to add his name 
Los 15 is still in Alpha Stage for our device will update AIMROM soon :)

**Comment by Anandnv** [comment]
@AryanKedare We are AOSP
Not LOS

**Comment by iamsj7** [comment]
@Anandnv 😂😂😂😂😂

**Comment by krasCGQ** [comment]
@Anandnv Lololololololol

**Comment by AryanKedare** [comment]
Yea 
But let one rom be stable so we can start compiling on other roms :/
Remember Lenovo A7000 Is MTK 
Pure AOSP Didn't Booted On Our device ;(

**Pull request merged**
