### PR TITLE
change maintainer for Lenovo P2(kuntao)

### PR DESCRIPTION
**Pull request by arghyac35**

### CODE REVIEW

**Comment by krasCGQ** [comment]
@arghyac35 Sounds like switching maintainers

**Comment by arghyac35** [comment]
@krasCGQ Did it.

**Comment by Rpingat** [comment]
Have you talked to Anand? Or the previous maintainer?

**Comment by arghyac35** [comment]
Yes, I have talked to Anand, he said to "make a pull inside settings edit that dudes(previous maintainer) name and replace it with yours".

**Comment by Anandnv** [comment]
@arghyac35 Merge it

**Pull request merged**
