### PR TITLE
Use correct icon for sim card

### PR DESCRIPTION
**Pull request by Rpingat**
- Instead of storage/sdcard icon, use the correct vector drawable sim card icon

Change-Id: Icf5f2e2a390b9c64162fbb17ce146b570ce228d8
AIM: adapted to Oreo

### CODE REVIEW

**Comment by iamsj7** [comment]
@Rpingat Thug

**Comment by krasCGQ** [comment]
@iamsj7 U w0t m8

**Comment by Rpingat** [comment]
Someone unmute me from AIM community

**Comment by krasCGQ** [comment]
@Rpingat @Anandnv @ShadowReaper1

**Comment by Rpingat** [comment]
They are offline

**Comment by krasCGQ** [comment]
@Rpingat ¯\_(ツ)_/¯

**Pull request closed without merging**
