### PR TITLE
Added Z00T & Z00L

### PR DESCRIPTION
**Pull request by riad236**

### CODE REVIEW

**Comment by krasCGQ** [comment]
@riad236 > ZenFone Laser 2
> ZenFone Laser Selfie

Rip Asus

**Comment by krasCGQ** [comment]
@riad236 .
> ZenFone Laser 2
> ZenFone Laser Selfie

Rip Asus

**Comment by govindpathak1** [comment]
@krasCGQ 😒😒ahhh...silly mistake 😐

**Comment by riad236** [comment]
wow..great mistake..LOL..just woke up and did..maybe thats y..

**Pull request merged**
